name: Publicar en NPM

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.4.0
      - name: Configurar Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile
      - name: Construir
        run: pnpm build
      - name: Cambiar al subdirectorio
        run: cd cli
      - uses: simenandre/publish-with-pnpm@v1
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}